Full library setup
wikibusiness/aioneo4j pull request #1
Opened 2017-04-10 12:21 UTC by a-urth

Tox, readme, requirements, tests, travis etc.

2017-04-10 12:30 UTC, hellysmile requested changes

2017-04-10 12:30 UTC, hellysmile commented on README.rst
> +        url = 'http://neo4j:neo4j@127.0.0.1:7474/'
url not used

2017-04-10 12:30 UTC, hellysmile commented on aioneo4j/client.py
>          @asyncio.coroutine
extra coroutine

2017-04-10 12:30 UTC, hellysmile commented on aioneo4j/transport.py
>          if self.session is not None:
remove lazy session at all

2017-04-26 22:47 UTC, hellysmile reviewed
Can You give a list of missing rest endpoints except transaction related?

2017-04-26 22:47 UTC, hellysmile commented on .travis.yml
> +  - NEO4J="3.1.3"
3.0.? Please

2017-04-26 22:47 UTC, hellysmile commented on requirements.txt
> +aiohttp==2.0.5
Copy all dec stuff from aioeladticsearch please

2017-04-26 22:47 UTC, hellysmile commented on tests/conftest.py
> +    finally:
Drop before and after evrything from neo4j

2017-04-26 22:48 UTC, hellysmile commented on README.rst
> +        url = 'http://neo4j:neo4j@127.0.0.1:7474/'
Fix this please

2017-04-27 08:21 UTC, a-urth commented on tests/conftest.py
> +    finally:
this is very bad idea to not to mock actual neo4j and drop everything from it.
if someone runs local neo4j and he runs tests he'll loose all data.

2017-04-27 08:34 UTC, a-urth commented on requirements.txt
> +aiohttp==2.0.5
copy what? and why? here are all required deps

2017-04-27 12:16 UTC, merged